spring.application.name=registration-service
server.port=${SERVER_PORT:8082}
management.endpoints.web.exposure.include=health,info,metrics
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer