spring.application.name=student-service
server.port=${SERVER_PORT:8081}
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.opentelemetry.tracing.export.otlp.endpoint=http://otel-collector:4317
management.opentelemetry.tracing.export.otlp.transport=grpc
management.tracing.sampling.probability=1.0
spring.kafka.template.observation-enabled=true
spring.kafka.listener.observation-enabled=true
spring.kafka.consumer.observation-enabled=true
spring.kafka.producer.observation-enabled=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.otlp.metrics.export.url=http://otel-collector:4318/v1/metrics
logging.pattern.correlation=[${spring.application.name:},%X{traceId:-},%X{spanId:-}]